---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      label-name: webapp
  replicas: 1
  template:
    metadata:
      labels:
        label-name: webapp
        release: "{{FAL_VER}}"
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:12
          command: ['sh', '-c',
                    'until pg_isready -h database -p 5432;
                     do echo waiting for database; sleep 2; done;']
        - name: run-alembic-migrations
          image: farshidashouri/fal:{{FAL_VER}}
          envFrom:
            - configMapRef:
                name: webapp-envs
          command: ['sh', '-c',
                    'alembic upgrade head']
      containers:
        - name: webapp
          image: farshidashouri/fal:{{FAL_VER}}
          envFrom:
            - configMapRef:
                name: webapp-envs
          volumeMounts:
            - name: webapp-persistant-storage
              mountPath: /data
      volumes:
        - name: webapp-persistant-storage
          hostPath:
            path: /mnt/webapp-storage/
            type: DirectoryOrCreate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      label-name: frontend
  replicas: 2
  template:
    metadata:
      labels:
        label-name: frontend
        release: "{{FAL_VER}}"
    spec:
      containers:
        - name: frontend
          image: farshidashouri/sapper-frontend:{{FAL_VER}}
