apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      label-name: webapp
  replicas: 1
  template:
    metadata:
      labels:
        label-name: webapp
        release: "{{FAL_VER}}"
    spec:
      containers:
      - name: webapp
        image: farshidashouri/fal:{{FAL_VER}}
        volumeMounts:
          - name: webapp-persistant-storage
            mountPath: /data
      volumes:
        - name: webapp-persistant-storate
          hostPath:
            path: /mnt/webapp-storage/
            type: DirectoryOrCreate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      label-name: frontend
  replicas: 2
  template:
    metadata:
      labels:
        label-name: frontend
        release: "{{FAL_VER}}"
    spec:
      containers:
      - name: frontend
        image: farshidashouri/sapper-frontend:{{FAL_VER}}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      label-name: queue
  replicas: 1
  template:
    metadata:
      labels:
        label-name: queue
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1
