apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      label-name: webapp
  replicas: 3
  template:
    metadata:
      labels:
        label-name: webapp
        release: "latest"
    spec:
      containers:
      - name: webapp
        image: farshidashouri/fal:{{FAL_VER}}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      label-name: queue
  replicas: 1
  template:
    metadata:
      labels:
        label-name: queue
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1
