version: "3.8"
services:
  
  database:
    image: postgres:12
    env_file: 
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 256M
            reservations:
                memory: 128M

    restart: always
    networks:
      - fal

  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./fleetman-nginx.conf:/etc/nginx/conf.d/dev.fleetman.com.conf:ro
      - ./cert:/etc/nginx/cert
    ports:
      - 80:80
      - 443:443
      - 10000:10000
    restart: always
    networks:
      - fal

  web:
    build:
      context: .
      dockerfile: Dockerfile.app
      target: local

    env_file: 
      - .env
    restart: always

    volumes:
      - ./app:/app/dev
      - ./data:/data

    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 512M
            reservations:
                memory: 128M
    
    depends_on:
      - database
    
    networks:
      - fal

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: local

    env_file: 
      - .env
    ports:
      - "3000:3000"
    restart: always

    volumes:
      - ./frontend:/frontend/dev

    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 512M
            reservations:
                memory: 128M
    
    depends_on:
      - web
    
    networks:
      - fal
    
volumes:
  db-data:
      driver: local


networks:
  fal:
