version: "3.8"
services:
  
  database:
    image: postgres:12
    env_file: 
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

    deploy:
        resources:
            limits:
                cpus: '0.5'
                memory: 128M
            reservations:
                memory: 64M

    restart: always
    networks:
      - priv-net

  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - 80:80
      - 443:443
      - 10000:10000
    restart: always
    networks:
      - priv-net

  web:
    build:
      context: .
      dockerfile: Dockerfile.app
      target: local

    env_file: 
      - .env
    restart: always

    volumes:
      - ./app:/app/dev
      - ./data:/data

    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 128M
            reservations:
                memory: 64M
    
    depends_on:
      - database
    
    networks:
      - priv-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: local

    env_file: 
      - .env
    ports:
      - "3000:3000"
    restart: always

    volumes:
      - ./frontend:/frontend/dev

    deploy:
        resources:
            limits:
                cpus: '0.5'
                memory: 128M
            reservations:
                memory: 64M
    depends_on:
      - web

    networks:
      - priv-net

    
volumes:
  db-data:
      driver: local


networks:
  priv-net:
