version: "3.8"
services:
  
  database:
    image: postgres:12
    env_file: 
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 256M
            reservations:
                memory: 128M

    restart: always
    networks:
      - fal

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: local 

    env_file: 
      - .env
    ports:
      - "8001:80"
    restart: always

    volumes:
      - ./app:/app/dev

    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 512M
            reservations:
                memory: 128M
    
    depends_on:
      - database
    
    networks:
      - fal
    
volumes:
  db-data:
      driver: local


networks:
  fal:
