---
apiVersion: v1
kind: Service
metadata:
  name: london-man-webapp

spec:
  # this defines which pods are going to be represented by the service.
  selector:
    label-name: webapp
    release: "{{FAL_VER}}"
  ports:
  - name: http
    port: 80
    targetPort: 80

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: london-man-frontend

spec:
  # this defines which pods are going to be represented by the service.
  selector:
    label-name: frontend
    release: "{{FAL_VER}}"
  ports:
  - name: http
    port: 3000
    targetPort: 3000

  type: NodePort
