---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  # this defines which pods are going to be represented by the service.
  selector:
    label-name: webapp
    release: "{{FAL_VER}}"
  ports:
  - name: http
    port: 80
    nodePort: 30009

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-frontend

spec:
  # this defines which pods are going to be represented by the service.
  selector:
    label-name: frontend
    release: "{{FAL_VER}}"
  ports:
  - name: http
    port: 3000
    nodePort: 30012

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  # this defines which pods are going to be represented by the service.
  selector:
    label-name: queue
  ports:
  - name: http
    port: 8161 
    nodePort: 30010

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-rabbitmq

spec:
  # this defines which pods are going to be represented by the service.
  selector:
    label-name: rabbitmq
  ports:
  - name: http
    port: 15672 
    nodePort: 30011

  type: NodePort
